// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Vite
// plugin that tells the Electron app where to look for the Vite-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_VITE_DEV_SERVER_URL: string;
declare const MAIN_WINDOW_VITE_NAME: string;

// Preload types
interface ThemeModeContext {
  toggle: () => Promise<boolean>;
  dark: () => Promise<void>;
  light: () => Promise<void>;
  system: () => Promise<boolean>;
  current: () => Promise<"dark" | "light" | "system">;
}
interface ElectronWindow {
  minimize: () => Promise<void>;
  maximize: () => Promise<void>;
  close: () => Promise<void>;
}

interface ElectronAPI {
  selectFile: () => Promise<string | null>;
  selectFolder: () => Promise<string | null>;
  saveImages: (baseFolder: string, files: { name: string; data: ArrayBuffer }[], subFolder: string) => Promise<string>;
  saveTempImage?: (data: ArrayBuffer, ext: string) => Promise<string>;
  downloadImageToTemp?: (url: string, ext: string) => Promise<string>;
  readFileAsDataUrl?: (filePath: string) => Promise<string>;
  openFileLocation?: (filePath: string) => Promise<void>;
}

interface ElectronStoreAPI {
  get: (key: string) => unknown;
  set: (key: string, value: unknown) => void;
}

declare interface Window {
  electronAPI?: ElectronAPI;
  electronStore?: ElectronStoreAPI;
  themeMode: ThemeModeContext;
  electronWindow: ElectronWindow;
  electronLogger?: {
    log: (...args: unknown[]) => void;
  };
}

declare module "*.png" {
  const value: string;
  export default value;
}
declare module "*.jpg" {
  const value: string;
  export default value;
}
